
#Spring Properties
spring:
  application:
    name: SpringSecurity-Data-Application
  servlet:
    multipart:
      enabled: false
      max-file-size: -1
      max-request-size: -1


  # Jpa Properties
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver

  jpa:
    generate-ddl: true
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        dialet: org.hibernate.dialect.H2Dialect

  # Spring Session properties
  devtools:
    restart:
      enabled: true
server:
  port: 8080
